# =============================================================================
# ANSIBLE/INVENTORY/HOSTS.YML - Inventaire Fode-DevOps
# =============================================================================
---
all:
  children:
    fode_devops_prod:
      hosts:
        fode-web-server:
          ansible_host: 54.76.235.211
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/bin/python3

      vars:
        # Variables spécifiques à l'environnement Fode-DevOps
        project_name: fode-devops
        environment: prod
        aws_region: eu-west-1
        
        # Informations infrastructure
        vpc_id: vpc-092b1d445c03c77d6
        subnet_id: subnet-0245c3ce9efdc755a
        instance_id: i-0b9f9c5b04ed3cab9
        s3_bucket: fode-devops-prod-enhdkatg
        
        # Configuration web
        web_port: 80
        ssl_port: 443
        
        # Packages à installer
        packages:
          - httpd
          - git
          - curl
          - wget
          - nano
          - htop
          - tree
          - unzip
          - nodejs
          - npm
