# =============================================================================
# ANSIBLE/INVENTORY/HOSTS.YML - Inventaire Fode-DevOps
# =============================================================================
---
all:
  children:
    fode_devops_prod:
      hosts:
        fode-web-server:
        # ✅ IP récupérée dynamiquement depuis Terraform
          ansible_host: "{{ terraform_outputs.instance_public_ip }}"
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/bin/python3
      vars:
        # Variables spécifiques à l'environnement Fode-DevOps
        project_name: fode-devops
        environment: prod
        aws_region: us-east-1
        
        # Variables récupérées dynamiquement depuis Terraform
        vpc_id: "{{ terraform_outputs.vpc_id }}"
        subnet_id: "{{ terraform_outputs.private_subnet_id }}"
        instance_id: "{{ terraform_outputs.instance_id }}"
        s3_bucket: "{{ terraform_outputs.s3_bucket_name }}"
        
        # Configuration web
        web_port: 80
        ssl_port: 443
        
        # Packages à installer
        packages:
          - httpd
          - git
          - curl
          - wget
          - nano
          - htop
          - tree
          - unzip
          - nodejs
          - npm
